# To use:
#
#   $ mamba env create -f environment.yml
#   $ mamba activate pyseamsdev
#
name: pyseamsdev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - pkg-config
  - clang
  # d-SEAMS deps
  - yaml-cpp
  - boost-cpp
  - fmt==9.0.0
  - eigen==3.4.0
  # Python
  - pdm
  - pybind11
